name: Randomizer
version: '1.1'
main: me.tigerx4.randomizer.Randomizer
api-version: '1.13'
author: TigerX4
commands:
  randomizer:
    description: "Command to enable/disable Randomizer"
    usage: "Usage: /<command> [start|stop]"