name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - TigerX6
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug as precisely as possible. You can also add some screenshots.
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which plugin version are you using?
      placeholder: ex. 1.4.0
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      description: Which version of Minecraft are you using?
      placeholder: ex. 1.20.1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste any relevant console output here.
      render: shell